name: lcg_linux_with_podio

on: [push, pull_request]

jobs:
  build-and-test-with-podio:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["dev3/x86_64-el9-clang16-opt",
              "dev4/x86_64-el9-clang16-opt",
              "dev4/x86_64-el9-gcc13-opt",
              "LCG_106/x86_64-el9-gcc13-opt"]
        CXX_STANDARD: [20]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: AIDASoft/podio
        path: podio
    - uses: key4hep/key4hep-actions/cache-external-data@main
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v5
      with:
        release-platform: ${{ matrix.LCG }}
        ccache-key: ccache-${{ matrix.LCG }}
        run: |
          STARTDIR=$(pwd)
          echo "::group::Build podio"
          cd podio
          echo "Building podio @"$(git log -1 --format=%H)
          cmake -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DENABLE_SIO=ON \
            -DENABLE_RNTUPLE=ON \
            -DENABLE_DATASOURCE=ON \
            -DBUILD_TESTING=OFF \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -G Ninja -B build
          cmake --build build --target install -- -k0
          source init.sh && source env.sh
          echo "::endgroup::"
          echo "::group::Build edm4hep"
          cd $STARTDIR
          echo "Building edm4hep"
          cmake -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
            -DUSE_EXTERNAL_CATCH2=OFF \
            -G Ninja -B build
          cmake --build build -- -k0
          ctest --test-dir build --output-on-failure
          cmake --build build --target install
          echo "::endgroup::"
          echo "::group::Test downstream usage"
          export CMAKE_PREFIX_PATH=$PWD/install:$CMAKE_PREFIX_PATH
          cd test/downstream-project-cmake-test
          cmake -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -G Ninja -B build
          cmake --build build -- -k0
          echo "::endgroup::"
