name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: edm4hep
    - uses: actions/checkout@v4
      with:
        repository: AIDASoft/podio
        path: podio
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v4
      with:
        container: el9
        view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
        run: |
          echo "::group::Build podio"
          cd ${GITHUB_WORKSPACE}/podio
          echo "Building podio @"$(git log -1 --format=%H)
          cmake -DCMAKE_CXX_STANDARD=20 \
            -DENABLE_SIO=ON \
            -DBUILD_TESTING=OFF \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
            -G Ninja -B build
          cmake --build build --target install
          source init.sh && source env.sh
          echo "::endgroup::"
          echo "::group::Run pre-commit"
          cd ${GITHUB_WORKSPACE}/edm4hep
          python3 -m venv /root/pre-commit-venv
          source /root/pre-commit-venv/bin/activate
          pip install pre-commit ruff
          pre-commit run --show-diff-on-failure \
            --color=always \
            --all-files
          echo "::endgroup::"
